### ISSUE TITLE
Needle tip issue

### ISSUE THREAD

**Issue by michaelwkudla** [brachify/brachify#1]
The issue is with the command in this block in channel.py (lines 124-129):
    # rest of the points
    for i in range(1, len(points) - 1):
        p1 = points[i]
        p2 = points[i + 1]
        cylinder = _rounded_pipe(p1, p2, radius)
        pipe = BRepAlgoAPI_Fuse(pipe, cylinder).Shape()

In particular, the command: BRepAlgoAPI_Fuse(pipe, cylinder).Shape()

Something about this makes the whole existing pipe go away. I can prove that the data is there by skipping some points. If i change the 1 to an 8:

    # rest of the points
    for i in range(8, len(points) - 1):
        p1 = points[i]
        p2 = points[i + 1]
        cylinder = _rounded_pipe(p1, p2, radius)
        pipe = BRepAlgoAPI_Fuse(pipe, cylinder).Shape()
See image. 

@nsmela do you have an intuition why this is happening? I don't know enough about how to debug that command exactly. 

![image](https://github.com/brachify/brachify/assets/25753746/382aaf5a-1b4a-44db-a11b-3ec0703fd1f9)

**Comment by michaelwkudla** [comment]
I found that adding: 
channel_points = np.round(channel_points,3)

I don't know why. Probably some floating point issues. Never a bad idea to round I guess!

**Comment by michaelwkudla** [comment]
Fixed wirh https://github.com/brachify/brachify/pull/2

**Comment by nsmela** [comment]
Whoa weird. My best guess is that the points along the curve are too close and caused a big. Maybe by rounding, the points move far enough away to be generated.
